export const REASON_FOR_VISIT = [
  "Follow-Up Visit",
  "Foreign body",
  "BOV",
  "Trauma",
  "Dizziness/Headaches",
  "Teary eyes",
  "Dry/Burning Sensation",
  "Redness",
  "Eye Pain",
  "Floaters",
  "FB Sensation",
  "Itchiness",
  "Eye Lid Mass",
  "Flashing of Lights",
  "Photophobia",
  "For VFT/FA/F-Photo/OCT",
  "Others",
];

export const MEDICAL_HISTORY = [
  "Diabetes",
  "Hypertension",
  "Asthma",
  "Arthritis",
  "Lung Problem",
  "Glaucoma",
  "Cancer",
  "Heart Disease",
  "Others",
];

export const MEDICAL_HISTORY_OBJECT = [
  { name: "Diabetes", code: "diabetes", id: 1 },
  { name: "Hypertension", code: "hypertension", id: 2 },
  { name: "Asthma", code: "asthma", id: 3 },
  { name: "Arthritis", code: "arthritis", id: 4 },
  { name: "Lung Problem", code: "lungProblem", id: 5 },
  { name: "Glaucoma", code: "glaucoma", id: 6 },
  { name: "Cancer", code: "cancer", id: 7 },
  { name: "Heart Disease", code: "heartDisease", id: 8 },
  { name: "Others", code: "others", id: 9 },
];

export const PREVIOUS_SURGERIES_OBJECT = [
  { name: "Cataract", code: "cataract", id: 1 },
  { name: "Pterygium", code: "pterygium", id: 2 },
  { name: "Glaucoma", code: "glaucomaSur", id: 3 },
  { name: "Retina", code: "retina", id: 4 },
  { name: "PRP", code: "prp", id: 5 },
  { name: "FLT", code: "flt", id: 6 },
  { name: "YAG-CAP", code: "yagCap", id: 7 },
  { name: "YAG-LI", code: "yagLi", id: 8 },
  { name: "ANTI-VEGF", code: "antiVegf", id: 9 },
  { name: "Others", code: "others", id: 10 },
];

export const PREVIOUS_SURGERIES = [
  "Cataract",
  "Pterygium",
  "Glaucoma",
  "Retina",
  "PRP",
  "FLT",
  "YAG-CAP",
  "YAG-LI",
  "ANTI-VEGF",
  "Others",
];

export const MONTHS = {
  "0": "January",
  "1": "February",
  "2": "March",
  "3": "April",
  "4": "May",
  "5": "June",
  "6": "July",
  "7": "August",
  "8": "September",
  "9": "October",
  "10": "November",
  "11": "December",
};

export const ERROR_MESSAGE = {
  REQUIRED: "Field is required",
};

export const PAYMENT_TYPE = ["With Payment", "Without Payment"];

export const patientRecordSearchParameterMapper = [
  {
    field: "quickSearchInput",
    label: "Quick Search",
  },
  {
    field: "recordNo",
    label: "Record No",
  },
  {
    field: "patientNo",
    label: "Patient No",
  },
  {
    field: "lastName",
    label: "Patient Last Name",
  },
  {
    field: "firstName",
    label: "Patient First Name",
  },
  {
    field: "middleName",
    label: "Patient Middle Name",
  },

  {
    field: "birthDate",
    label: "Birth Date",
  },
  {
    field: "dateFrom",
    label: "Record Date From",
  },
  {
    field: "dateTo",
    label: "Record Date To",
  },
  {
    field: "followUpDate",
    label: "Patient FollowUp Date",
  },
  {
    field: "statusName",
    label: "Record Status",
  },
  {
    field: "surgery",
    label: "Surgery",
  },
  {
    field: "doctorName",
    label: "Doctor",
  },
];

export const RECORD_STATUSES = [
  {
    label: "For Doctors checkup",
    value: "1",
  },
  {
    label: "Cancelled",
    value: "2",
  },
  {
    label: "Done",
    value: "3",
  },
  {
    label: "For Followup Checkup",
    value: "4",
  },
  {
    label: "For diagnostic examination",
    value: "5",
  },
  {
    label: "For Charging to PhilHealth",
    value: "6",
  },
];

export const VISIT_TYPE = ["OPERATION", "CONSULTATION", "DIAGNOSTIC"];

export const NATIONALITY_LIST = [
  "Filipino",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Antiguans",
  "Argentinean",
  "Armenian",
  "Australian",
  "Austrian",
  "Azerbaijani",
  "Bahamian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Barbudans",
  "Batswana",
  "Belarusian",
  "Belgian",
  "Belizean",
  "Beninese",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Brazilian",
  "British",
  "Bruneian",
  "Bulgarian",
  "Burkinabe",
  "Burmese",
  "Burundian",
  "Cambodian",
  "Cameroonian",
  "Canadian",
  "Cape Verdean",
  "Central African",
  "Chadian",
  "Chilean",
  "Chinese",
  "Colombian",
  "Comoran",
  "Congolese",
  "Costa Rican",
  "Croatian",
  "Cuban",
  "Cypriot",
  "Czech",
  "Danish",
  "Djibouti",
  "Dominican",
  "Dutch",
  "East Timorese",
  "Ecuadorean",
  "Egyptian",
  "Emirian",
  "Equatorial Guinean",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Finnish",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guatemalan",
  "Guinea-Bissauan",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Herzegovinian",
  "Honduran",
  "Hungarian",
  "I-Kiribati",
  "Icelander",
  "Indian",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Irish",
  "Israeli",
  "Italian",
  "Ivorian",
  "Jamaican",
  "Japanese",
  "Jordanian",
  "Kazakhstani",
  "Kenyan",
  "Kittian and Nevisian",
  "Kuwaiti",
  "Kyrgyz",
  "Laotian",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Liechtensteiner",
  "Lithuanian",
  "Luxembourger",
  "Macedonian",
  "Malagasy",
  "Malawian",
  "Malaysian",
  "Maldivan",
  "Malian",
  "Maltese",
  "Marshallese",
  "Mauritanian",
  "Mauritian",
  "Mexican",
  "Micronesian",
  "Moldovan",
  "Monacan",
  "Mongolian",
  "Moroccan",
  "Mosotho",
  "Motswana",
  "Mozambican",
  "Namibian",
  "Nauruan",
  "Nepali",
  "New Zealander",
  "Nicaraguan",
  "Nigerian",
  "Nigerien",
  "North Korean",
  "Northern Irish",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Palauan",
  "Panamanian",
  "Papua New Guinean",
  "Paraguayan",
  "Peruvian",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Russian",
  "Rwandan",
  "Saint Lucian",
  "Salvadoran",
  "Samoan",
  "San Marinese",
  "Sao Tomean",
  "Saudi",
  "Scottish",
  "Senegalese",
  "Serbian",
  "Seychellois",
  "Sierra Leonean",
  "Singaporean",
  "Slovakian",
  "Slovenian",
  "Solomon Islander",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Sri Lankan",
  "Sudanese",
  "Surinamer",
  "Swazi",
  "Swedish",
  "Swiss",
  "Syrian",
  "Taiwanese",
  "Tajik",
  "Tanzanian",
  "Thai",
  "Togolese",
  "Tongan",
  "Trinidadian/Tobagonian",
  "Tunisian",
  "Turkish",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Uruguayan",
  "Uzbekistani",
  "Venezuelan",
  "Vietnamese",
  "Welsh",
  "Yemenite",
  "Zambian",
  "Zimbabwean",
];
